//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day2Paper2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public string Airplane_ID { get; set; }
        public string Model { get; set; }
        public byte Number_of_Seats { get; set; }
        public string Seat_Configuration { get; set; }
    }
}
