//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day2Paper2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public string Flight_ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.TimeSpan Departure_time { get; set; }
        public System.TimeSpan Arrival_time { get; set; }
    }
}
