//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day2Paper2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itenerary
    {
        public string Booking_Reference { get; set; }
        public string Contact_details { get; set; }
        public string Status { get; set; }
        public System.DateTime Flight_Date { get; set; }
    }
}
