//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day2Paper2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string Ticket_ID { get; set; }
        public string Booking_Reference { get; set; }
        public string Passenger { get; set; }
        public string Ticket_Category { get; set; }
        public string Status { get; set; }
        public string Seat { get; set; }
        public Nullable<int> Number_of_Baggage { get; set; }
        public Nullable<int> Weight_of_Baggage { get; set; }
    
        public virtual Passenger Passenger1 { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
    }
}
