//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day2Paper2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketCategory()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string Ticket_Category { get; set; }
        public string Class { get; set; }
        public string Flight { get; set; }
        public string Airplane { get; set; }
        public string Seats { get; set; }
        public int Number_of_Baggage { get; set; }
        public int Weight_of_Baggage { get; set; }
        public int Cancellation_fee { get; set; }
        public int Change_fee { get; set; }
        public int Fare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
